### ISSUE TITLE
ED crashes on planetary preparation at startup

### ISSUE THREAD

**Issue by arne-fuchs** [redmcg/wine-mono#6] opened 2021-05-19 21:35 UTC
Game crashes at planetary prepareation phase. Can't send crash report because of an nullpointer.

**Comment by arne-fuchs** [comment] 2021-05-19 21:47
Workaround: Hit Shift+Tab fast so Steam Overlay opens and closes fast. This way you can enter the game menu

**Comment by sparky8251** [comment] 2021-05-20 17:24
This happens to me too, but I cant seem to get the workaround to work.

Think it might be related to the fact I use an AMD GPU. Most of the success reports on protondb are nVidia GPUs, and the AMD users all seem to have additional issues with a few exceptions.

**Comment by sparky8251** [comment] 2021-05-20 17:54
Deeper I look, more I think this is the issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/4533

Apparently mesa had a regression that impacted planet gen just for polaris GPUs.

The fix has currently been merged into mesa's master, but that was only 3 weeks ago. Unsure if a version has been cut with the fix yet. Regardless, a git install *should* fix the issue for people with similar hardware and software setups to mine.

Compiling mesa-git now on my system. Will report if it helped or not when I can finally confirm it.

EDIT: Confirmed fix was compiled into mesa for me. Did not work though...

**Comment by kakra** [comment] 2021-05-21 08:19
I don't think this is a wine-mono issue at all...

**Comment by arne-fuchs** [comment] 2021-05-21 09:40
> This happens to me too, but I cant seem to get the workaround to work.
> 
> Think it might be related to the fact I use an AMD GPU. Most of the success reports on protondb are nVidia GPUs, and the AMD users all seem to have additional issues with a few exceptions.

I have a system with a vega 64 system so the issue is on the amd site. 
The issue is gone if the planet preparation was loaded once. 

> I don't think this is a wine-mono issue at all...

Right now I hear that both sides are saying, that it is not their issue. Mesa and Wine-Mono.
The problem needs to be identified.

**Comment by kakra** [comment] 2021-05-21 10:59
.NET (wine-mono) is only needed by the launcher (the black window with the news, updates, and elite-version chooser), it has nothing to do with shader preparation.

If anything, the problem is either mesa (for GPUs using mesa), or DXVK (if you're using that which you probably do), or some Direct3D component in wine (most unlikely), and NVIDIA (proprietary) brings its own graphics stack and does not use/need mesa.

For me, it just runs fine with wine-mono and NVIDIA, with Proton-patched DXVK. This kind of puts mesa in the deal.

If you are using Proton, you should run with `PROTON_LOG=1 %command%` and look at the generated log: When the game crashes/freezes, do you see anything related to shaders, DXVK or mono? You should upload it to gist and link the file in the Proton tracker, I don't think it's something mono-related. The Proton devs may ask you for a log especially tailored toward shader logging.

Other things to try: Disable shader pre-caching in the Steam client, clear shader caches (mesa and Steam), after clearing the caches, the first start of the game may hang several minutes while you should see the CPU doing a lot of work, be patient. But it may work around corrupted shader caches which could make the planetary preparation crash.

**Comment by alsh** [comment] 2021-05-21 12:26
DXVK has a workaround for compiling planet shaders for quite some time. Isn't this related? May be DXVK does not recognize executable after update anymore?

**Comment by LeagueOfFreeWorlds** [comment] 2021-05-21 18:18
I've attempted to patch proton with DXVK, and have ran into the same issue of the game crashing upon planet generation. Additionally I disabled shader pre-caching on Steam but that didn't produce any difference apart from having to wait for shaders to process. I'm uncertain whether or not I patched proton correctly (following this guide: https://www.reddit.com/r/linux_gaming/comments/99imjf/psa_steam_proton_currently_ships_dxvk_with/), or something else wrong entirely, given my lack of understanding.
I did install `amd-radeon` mesa driver (given I have both AMD CPU and GPU), but that also didn't seem to make a difference. (https://archlinux.org/packages/?name=vulkan-radeon). However, given that this is an issue being mentioned as on AMD's side of things, I suppose that's why it doesn't function properly. 
> If you are using Proton, you should run with `PROTON_LOG=1 %command%` and look at the generated log

Sorry, I don't know what you mean, how do I generate a log exactly?

**Comment by sparky8251** [comment] 2021-05-22 13:55
Yeah... Workaround here def doesnt work for me. I see a vega user here reporting it does, but my GPU is the RX 5700XT, so I'm kinda leaning towards mesa myself.

**Comment by Xiretza** [comment] 2021-05-22 14:01
I can add that the workaround (opening steam overlay when the game starts, then leaving it open and the window untouched until the main menu loads) worked for me on my RX 580 when launched from steam (with proton 6.3-4).

**Comment by LeagueOfFreeWorlds** [comment] 2021-05-22 23:26
Okay, so I believe I found a solution since it finally resolved the issue for me. I'm now more convinced that the issue is likely on behalf of wine-mono, since after reinstalling the msi package, the game successfully launched. (https://github.com/redmcg/wine-mono/wiki#with-protontricks) I am a little inexperienced with wine-mono and protontricks, so I don't know the exact nuances that resolved the problem.

**Comment by kakra** [comment] 2021-05-22 23:29
Or re-installing triggered something in Proton: Proton may replace a lot of DLLs to default if it detects some prefix changes.

**Comment by arne-fuchs** [comment] 2021-05-27 06:37
Are still people having this issue? Else I would close it if there are no more reports for it.

**Closed as completed** 2021-05-31 09:10 UTC
